### ISSUE TITLE
Sorting and storing an external file

### ISSUE THREAD

**Issue by jmalicevic** [stxxl/stxxl#66]
Hi,

I followed your example of stxxl sorter to sort an external file and save the result in another file by:
creating a vector with a file as input, streamifying it, creating a sort_stream from this input stream. Now at this point, is the data already sorted or only partially sorted?

The last step is materliazing  this sort_stream into a vector mapped to the output file. Is the sorting done in this step too or is it just a copy from the temporary file into the destination file?

Thanks for your answer.

**Comment by manpen** [comment]
Hi,

> I followed your example of stxxl sorter to sort an external file and save the result in another file by:
> creating a vector with a file as input, streamifying it, creating a sort_stream from this input stream. Now at this point, is the data already sorted or only partially sorted?

The constructor of `stxxl::stream::sort` consumes the input stream completely and creates so-called runs (size is governed by `memory_to_use` and assumed to fit into RAM). Each run is basically some portion of the input stream of fixed length that is locally sorted before it is written temporarily to disk (if necessary). Hence, in order to obtain a globally sorted sequence, the runs need to be merged. In many cases, this merging can be done online while the `sort` stream is consumed itself (e.g., during materializing). If there are, however, too many runs they will be recursively merged during in the c'tor (i.e. we get fewer but longer sorted subsequences).

> The last step is materliazing this sort_stream into a vector mapped to the output file. Is the sorting done in this step too or is it just a copy from the temporary file into the destination file?

In general (assuming large enough inputs), after the execution of `stxxl::stream::sort`'s constructor data is partially sorted and additionally merging is performed as you consume the sort-stream.
